### ISSUE TITLE
JOSS Review: Units in legend/colorbar title

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#105]
Based on issue #101:

> For all plots, it would be good to show the units along with the legend, and to perhaps somehow annotate the chosen variable and timestep or temporal aggregation method (I see that user can input a custom legend title as one option; if that's preferred then would help to mention it in the docs).

- [ ] Add default legend/color bar title to each plot that includes parameter, value, and units, e.g., "Base Demand at hr 10 [m3/s]", "Mean Pressure [psi]". Don't need to implement this for custom/excel data plots.

**Comment by tylertrimble** [comment]
Titles are added by default using a function with a bunch of dictionaries defining the strings that should be used. This also works without defining the unit argument in all the drawing functions. 

Example of before and after change:
![image](https://user-images.githubusercontent.com/102005076/222941281-e60941d6-af0f-4a5e-ae89-e958f31e77bf.png)
--------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/102005076/222941648-a4c6ca3b-c5a3-4afe-aa56-a5538cd3c81b.png)

Note that quality here means water age. It is only quality and not water age because the quality parameter can take on different meanings depending on the settings of the .inp file.
