### ISSUE TITLE
Continuous subplots

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#108]
Continuation of #95: When generating subplots with continuous node/link plots, fix code so that color bars appear in the correct place (not all one on top of each other on the right edge of the figure).

**Comment by tylertrimble** [comment]
Example of the problem:
![image](https://user-images.githubusercontent.com/102005076/222632123-ea157ae5-f88d-4a4c-addb-878a80ff1fc1.png)

Here, the two color bars should be drawn next to their respective axis. However, they are instead stacked due to the color bar axes being appened relative to the figure, not the axes.

To solve this, the position of the axes on the figure was taken into account. Additionally, two new arguments were added: color_bar_width and color_bar_height which came about due to changing how color bar positions are determined. 

Results after the fix was implemented:
![image](https://user-images.githubusercontent.com/102005076/222633085-f0b79fd2-3e54-4d35-ba99-f295a5b85ea6.png)
--------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/102005076/222633143-ddadf776-6537-4142-bef4-92af61300bdc.png)
--------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/102005076/222633180-e8d4ba5d-5bd6-4703-bbb5-51ae82878177.png)

**Comment by meghnathomas** [comment]
@tylertrimble excellent job!
