### ISSUE TITLE
JOSS REVIEW: DeprecationWarning: invalid escape sequence '\,'

### ISSUE THREAD

**Issue by tylertrimble** [tylertrimble/viswaternet#115]
Not sure what this is about? Leaving this here to look at later.

**Comment by meghnathomas** [comment]
@tylertrimble looks like this has to do with the way the flow rate units are written in the docstring of this file!
https://github.com/tylertrimble/viswaternet/blob/master/viswaternet/utils/unit_conversion.py

which is interesting because it renders perfectly fine in the API docs:
https://viswaternet.readthedocs.io/en/latest/source/viswaternet.utils.html#module-viswaternet.utils.unit_conversion

**Comment by meghnathomas** [comment]
fixed with commit f6ea50e (tyler let me know if you still see it for some reason, looks like it's been resolved to me)
