### ISSUE TITLE
Frame Rate for Animation

### ISSUE THREAD

**Issue by mfrankel923** [tylertrimble/viswaternet#132]
The parameter "fps" in the animation module is not in the correct units. The duration is expressed in hundredths of a second. So, with the default value of 3, the entire gif will animate in 3 hundredths of a second. 

I suggest updating the function instructions to specify the units, as well as change the default value from 3 to 3000 to get a duration of 3 seconds.

See here for the description of the duration parameter in imageio:

https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pillow_legacy.html#parameters-for-saving

**Comment by tylertrimble** [comment]
Hi Matthew, thanks for pointing this out! I didn't notice that duration is in hundredths of a second for GIFS only, quite strange that it is defined in seconds in every instance except for .GIF files. I pushed a quick change that sets the duration to be (100/fps) so for the default value of 3 frames per second the duration of each frame will be 333ms instead of 3.3ms.
