### ISSUE TITLE
pump line style

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#86]
changing pump line style doesn't reflect in the legend!

![image](https://user-images.githubusercontent.com/74310847/201230152-15a38a9d-f33a-4bbc-b830-5bdc649fb216.png)

![image](https://user-images.githubusercontent.com/74310847/201230179-a8cccd56-96d0-4d61-8a93-833dbd637586.png)

maybe there are some other issues like this?
 
+ there's a black line under the pump that shows up even when we change the line style

**Comment by tylertrimble** [comment]
Aha, the black line under the pump is probably because the link is still being drawn when draw_base_elements is called. I never noticed before because we didn't have a line style option until very recently.  

On the topic of the line style not being reflected on the legend is because patches are being used because the lines were very thin without them, however it seems necessary now to drop the patches.
